version: '3.8'
services:
  redis:
    image: 'redis:latest'
    container_name: redis-server
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: rabbitmq-server
    ports:
      - '5672:5672' 
      - '15672:15672' 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  redisdata:
  rabbitmqdata: